name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Node.js dependencies
      run: npm install

    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: |
          venv
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Set up Python virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install pipreqs || echo "pipreqs already installed"
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Update requirements.txt
      run: |
        source venv/bin/activate
        pipreqs . --force
  
    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found."; fi
