name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Node.js dependencies
      run: npm install

    - name: Update requirements.txt
      run: |
        source /home/mg/actions-runner/_work/thunderbyte/thunderbyte/bin/activate
        pipreqs . --force

    - name: Commit and push updated requirements.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add requirements.txt || echo "No changes to commit."
        git commit -m 'Update requirements.txt' || echo "Nothing to commit."
        git push origin main || echo "Nothing to push."

    - name: Install Python dependencies
      run: |
        source /home/mg/actions-runner/_work/thunderbyte/thunderbyte/bin/activate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found."; fi










  
